### ISSUE TITLE
Unwrapped string: 'Select all that apply'

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-exercise-perseus-plugin#92] opened 2017-06-15 01:24 UTC
'Select all that apply' strings in exercises are in English for KA-Swahili

![image](https://user-images.githubusercontent.com/5150483/27161203-a9891b44-512e-11e7-8db3-1290f94ea56c.png)

Link to exercise on demo site: https://sw-instantschools.learningequality.org/learn/#/topics/93a5bfcfa2a74962be843288aefcfc0e/content/0a8590639436473fa4a3970eb805984e

**Comment by rtibbles** [comment] 2017-06-15 03:45
Duplicate of #90.

**Closed by rtibbles** 2017-06-15 03:45 UTC
